# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge-service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils_pb2 as utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65\x64ge-service.proto\x12\x03\x61pi\x1a\x0butils.proto24\n\x0b\x45\x64geService\x12%\n\tHeartbeat\x12\n.api.Empty\x1a\n.api.Empty\"\x00\x42-Z+github.com/wireless-monkeys/backend/pkg/apib\x06proto3')



_EDGESERVICE = DESCRIPTOR.services_by_name['EdgeService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/wireless-monkeys/backend/pkg/api'
  _EDGESERVICE._serialized_start=40
  _EDGESERVICE._serialized_end=92
# @@protoc_insertion_point(module_scope)
